### DISCUSSION TITLE
2.1.0

### DISCUSSION THREAD

**Discussion by jmcollin78** [jmcollin78/solar_optimizer#75] [Announcements]
## What's Changed

* Issue #66 add reload service by @jmcollin78 in https://github.com/jmcollin78/solar_optimizer/pull/71
* Issue #70 add min on time per day min by @jmcollin78 in https://github.com/jmcollin78/solar_optimizer/pull/74

To use this the #70 feature, you should:
1. read carefully the README to learn how it works,
2. change the integration configuration (parameters / integration / solar optimizer / configure) and update the reset time (when the total activation duration is resetted ; ie the begining of the day). It has been set to "05:00" by default,
3. update your configuration.yaml (or solar_optimizer.yaml if you have externalized it) and add some configuration for device that should be activated at a minimum duration: `offpeak_time` and `min_on_time_per_day_min. See readme for their meaning.

You have example in the readme:
```
solar_optimizer:
....
  devices:
    ....
    - name: "Water boiler"
      # 2 hours per day maximum
      max_on_time_per_day_min: 120
      # 1h per day minimum ...
      min_on_time_per_day_min: 60
      # ... starting at 22:30
      offpeak_time: "22:30"
```

This will start you Water boiler at 22:30 if it has not been activated for at least 60 min per day even if the solar production has been too weak. It will be activated until the `max_on_time_per_day_min` is reach or the reset time (cf. point 2). If `max_on_time_per_day_min` is not set, it will be activated during all the off-peak hours.

Don't hesitate to make some remarks in the comment of the associated discussion

**Full Changelog**: https://github.com/jmcollin78/solar_optimizer/compare/2.0.0...2.1.0

<hr /><em>This discussion was created from the release <a href='https://github.com/jmcollin78/solar_optimizer/releases/tag/2.1.0'>2.1.0</a>.</em>
