### DISCUSSION TITLE
probleme à l'installation

### DISCUSSION THREAD

**Discussion by Chrisdie59** [jmcollin78/solar_optimizer#91] [Q&A] [answered]
Bonsoir,
J'ai parametrer mes sensor sur la page d'installation mais j'ai ces erreurs

Enregistreur: homeassistant.setup
Source: setup.py:416
S'est produit pour la première fois: 20:19:37 (1 occurrences)
Dernier enregistrement: 20:19:37

Error during setup of component solar_optimizer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/solar_optimizer/__init__.py", line 122, in async_setup
    hass.data[DOMAIN]["coordinator"] = coordinator = SolarOptimizerCoordinator(
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~^
        hass, solar_optimizer_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/solar_optimizer/coordinator.py", line 65, in __init__
    raise err
  File "/config/custom_components/solar_optimizer/coordinator.py", line 57, in __init__
    for _, device in enumerate(config.get("devices")):
                               ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

Pour info je n'ai pas encore déclarer d'appareil dans le fichier solar_optimizer.yaml

Merci de vos eclairages

**Comment by jmcollin78** [comment]
Hello,

Ta configuration n'est pas conforme. Regarde bien les exemples dans le readme, vérifie bien l'indentation, au pire donne moi ton fichier de conf (en formattant avec le bouton <>).

La configuration est obligatoire pour que l'intégration fonctionne.

**Reply by Chrisdie59** [reply]
ok je regarde dans le readme et je reviens vers vous

**Reply by jmcollin78** [reply]
ou donne moi le fichier de conf en le formattant avec <>.

**Reply by Chrisdie59** [reply]
`""" Le Config Flow """

import logging
import voluptuous as vol

from homeassistant.core import callback
from homeassistant.config_entries import (
    ConfigFlow,
    FlowResult,
    OptionsFlow,
    ConfigEntry,
)
from homeassistant.components.sensor import DOMAIN as SENSOR_DOMAIN
from homeassistant.components.input_number import DOMAIN as INPUT_NUMBER_DOMAIN
from homeassistant.helpers import selector
import homeassistant.helpers.config_validation as cv
from homeassistant.exceptions import HomeAssistantError

from .const import DOMAIN, validate_time_format, DEFAULT_RAZ_TIME

_LOGGER = logging.getLogger(__name__)


solar_optimizer_schema = {
    vol.Required("refresh_period_sec", default=300): int,
    vol.Required("power_consumption_entity_id"): selector.EntitySelector(
        selector.EntitySelectorConfig(domain=[SENSOR_DOMAIN, INPUT_NUMBER_DOMAIN])
    ),
    vol.Required("power_production_entity_id"): selector.EntitySelector(
        selector.EntitySelectorConfig(domain=[SENSOR_DOMAIN, INPUT_NUMBER_DOMAIN])
    ),
    vol.Required("sell_cost_entity_id"): selector.EntitySelector(
        selector.EntitySelectorConfig(domain=[SENSOR_DOMAIN, INPUT_NUMBER_DOMAIN])
    ),
    vol.Required("buy_cost_entity_id"): selector.EntitySelector(
        selector.EntitySelectorConfig(domain=[SENSOR_DOMAIN, INPUT_NUMBER_DOMAIN])
    ),
    vol.Required("sell_tax_percent_entity_id"): selector.EntitySelector(
        selector.EntitySelectorConfig(domain=[INPUT_NUMBER_DOMAIN])
    ),
    vol.Optional("smooth_production", default=True): cv.boolean,
    vol.Optional("battery_soc_entity_id"): selector.EntitySelector(
        selector.EntitySelectorConfig(domain=[SENSOR_DOMAIN, INPUT_NUMBER_DOMAIN])
    ),
    vol.Optional("raz_time", default=DEFAULT_RAZ_TIME): str,
}


class SolarOptimizerConfigFlow(ConfigFlow, domain=DOMAIN):
    """La classe qui implémente le config flow pour notre DOMAIN.
    Elle doit dériver de FlowHandler"""

    # La version de notre configFlow. Va permettre de migrer les entités
    # vers une version plus récente en cas de changement
    VERSION = 1
    _user_inputs: dict = {}

    async def async_step_user(self, user_input: dict | None = None) -> FlowResult:
        """Gestion de l'étape 'user'. Point d'entrée de notre
        configFlow. Cette méthode est appelée 2 fois :
        1. une première fois sans user_input -> on affiche le formulaire de configuration
        2. une deuxième fois avec les données saisies par l'utilisateur dans user_input -> on sauvegarde les données saisies
        """
        user_form = vol.Schema(solar_optimizer_schema)

        if user_input is None:
            _LOGGER.debug(
                "config_flow step user (1). 1er appel : pas de user_input -> on affiche le form user_form"
            )
            return self.async_show_form(step_id="user", data_schema=user_form)

        try:
            validate_time_format(user_input.get("raz_time"))
        except vol.Invalid:
            errors = {"raz_time": "format_time_invalid"}
            return self.async_show_form(
                step_id="user",
                data_schema=self.add_suggested_values_to_schema(
                    data_schema=user_form,
                    suggested_values=user_input,
                ),
                errors=errors,
            )

        # 2ème appel : il y a des user_input -> on stocke le résultat
        self._user_inputs.update(user_input)
        _LOGGER.debug(
            "config_flow step2 (2). L'ensemble de la configuration est: %s",
            self._user_inputs,
        )

        return self.async_create_entry(title="SolarOptimizer", data=self._user_inputs)

    @staticmethod
    @callback
    def async_get_options_flow(config_entry: ConfigEntry):
        """Get options flow for this handler"""
        return SolarOptimizerOptionsFlow(config_entry)

    async def validate_input(self, data: dict) -> None:
        """Validate the user input allows us to connect."""
        validate_time_format(data.get("raz_time"))


class SolarOptimizerOptionsFlow(OptionsFlow):
    """The class which enable to modified the configuration"""

    _user_inputs: dict = {}
    config_entry: ConfigEntry = None

    def __init__(self, config_entry: ConfigEntry) -> None:
        """Initialisation de l'option flow. On a le ConfigEntry existant en entrée"""
        self.config_entry = config_entry
        # On initialise les user_inputs avec les données du configEntry
        self._user_inputs = config_entry.data.copy()
        if self._user_inputs.get("raz_time") is None:
            self._user_inputs["raz_time"] = DEFAULT_RAZ_TIME

    async def async_step_init(self, user_input: dict | None = None) -> FlowResult:
        """Gestion de l'étape 'user'. Point d'entrée de notre
        configFlow. Cette méthode est appelée 2 fois :
        1. une première fois sans user_input -> on affiche le formulaire de configuration
        2. une deuxième fois avec les données saisies par l'utilisateur dans user_input -> on sauvegarde les données saisies
        """
        user_form = vol.Schema(solar_optimizer_schema)

        if user_input is None:
            _LOGGER.debug(
                "config_flow step user (1). 1er appel : pas de user_input -> on affiche le form user_form"
            )
            return self.async_show_form(
                step_id="init",
                data_schema=self.add_suggested_values_to_schema(
                    data_schema=user_form,
                    suggested_values=self._user_inputs,
                ),
            )

        try:
            validate_time_format(user_input.get("raz_time"))
        except vol.Invalid:
            errors = {"raz_time": "format_time_invalid"}

            return self.async_show_form(
                step_id="init",
                data_schema=self.add_suggested_values_to_schema(
                    data_schema=user_form,
                    suggested_values=user_input,
                ),
                errors=errors,
            )

        # 2ème appel : il y a des user_input -> on stocke le résultat
        self._user_inputs.update(user_input)
        _LOGGER.debug(
            "config_flow step_user (2). L'ensemble de la configuration est: %s",
            self._user_inputs,
        )

        # On appelle le step de fin pour enregistrer les modifications
        return await self.async_end()

    async def async_end(self):
        """Finalization of the ConfigEntry creation"""
        _LOGGER.info(
            "Recreation de l'entry %s. La nouvelle config est maintenant : %s",
            self.config_entry.entry_id,
            self._user_inputs,
        )

        # Modification des data de la configEntry
        # (et non pas ajout d'un objet options dans la configEntry)
        self.hass.config_entries.async_update_entry(
            self.config_entry, data=self._user_inputs
        )
        # Suppression de l'objet options dans la configEntry
        return self.async_create_entry(title=None, data=None)

    def validate_input(self, data: dict) -> None:
        """Validate the user input allows us to connect."""
        try:
            validate_time_format(data.get("raz_time"))
        except vol.Invalid as err:
            raise HomeAssistantError("raz_time") from err
`

**Reply by Chrisdie59** [reply]
c'est bien celui la ?

**Reply by jmcollin78** [reply]
Non la configuration que tu as mis dans ton `configuration.yaml`. Ca c'est le code.

Ca ressemble à ça : 
```yaml
algorithm:
   initial_temp: 1000
   min_temp: 0.1
   cooling_factor: 0.95
   max_iteration_number: 1000
devices:
   - name: "<equipment name>"
     entity_id: "switch.xxxxx"
...
```

**Reply by Chrisdie59** [reply]
voila ce que j'ai lis dans le configurateur.yaml  solar_optimizer: !include solar_optimizer.yaml et le code du fichier solar_optimizer.yaml  je precise que le fichier est au meme niveau que le configurateur `algorithm:
   initial_temp: 1000
   min_temp: 0.1
   cooling_factor: 0.95
   max_iteration_number: 1000
devices:
   - name: "cumulus"
     entity_id: "switch.prise_cumulus_commutateur"
     power_max: 505
     check_usable_template: "{{ <the template which is True if the equipment is usable> }}"
     duration_min: 60
     duration_stop_min: 60
     action_mode: "service_call"
     activation_service: "switch.turn_on"
     deactivation_service: "switch.turn_off"
     battery_soc_threshold: <the state of charge minimal to use this device>
     max_on_time_per_day_min: 360
     offpeak_time: 23:30
     min_on_day_per_day_min: 359`

**Reply by Chrisdie59** [reply]
`algorithm:
   initial_temp: 1000
   min_temp: 0.1
   cooling_factor: 0.95
   max_iteration_number: 1000
devices:
   - name: "cumulus"
     entity_id: "switch.prise_cumulus_commutateur"
     power_max: 505
     check_usable_template: "{{ <the template which is True if the equipment is usable> }}"
     duration_min: 60
     duration_stop_min: 60
     action_mode: "service_call"
     activation_service: "switch.turn_on"
     deactivation_service: "switch.turn_off"
     battery_soc_threshold: <the state of charge minimal to use this device>
     max_on_time_per_day_min: 360
     offpeak_time: 23:30
     min_on_day_per_day_min: 359`

**Reply by jmcollin78** [reply]
Formatte le avec le bouton <> sinon on ne voit rien. Ca doit ressembler à ce que j'ai posté

**Reply by Chrisdie59** [reply]
algorithm:
   initial_temp: 1000
   min_temp: 0.1
   cooling_factor: 0.95
   max_iteration_number: 1000
devices:
   - name: "cumulus"
     entity_id: "switch.prise_cumulus_commutateur"
     power_max: 505
     check_usable_template: "{{ <the template which is True if the equipment is usable> }}"
     duration_min: 60
     duration_stop_min: 60
     action_mode: "service_call"
     activation_service: "switch.turn_on"
     deactivation_service: "switch.turn_off"
     battery_soc_threshold: <the state of charge minimal to use this device>
     max_on_time_per_day_min: 360
     offpeak_time: 23:30
     min_on_day_per_day_min: 359``

**Comment by Chrisdie59** [comment]
```
`algorithm:
   initial_temp: 1000
   min_temp: 0.1
   cooling_factor: 0.95
   max_iteration_number: 1000
devices:
   - name: "cumulus"
     entity_id: "switch.prise_cumulus_commutateur"
     power_max: 505
     check_usable_template: "{{ <the template which is True if the equipment is usable> }}"
     duration_min: 60
     duration_stop_min: 60
     action_mode: "service_call"
     activation_service: "switch.turn_on"
     deactivation_service: "switch.turn_off"
     battery_soc_threshold: <the state of charge minimal to use this device>
     max_on_time_per_day_min: 360
     offpeak_time: 23:30
     min_on_day_per_day_min: 359`
```

**Reply by jmcollin78** [reply]
Tu as une quote en trop tout au début. `algorithm` doit être aligné sur `devices`.

`<the template which is True if the equipment is usable>` : il faut mettre un template ca ce n'est pas un template. Mets `{{ True }}` pour l'instant.

`<the state of charge minimal to use this device>` :  pareil ici il faut remplacer le texte ou supprimer la ligne `battery_soc_threshold`

**Reply by jmcollin78** [reply]
Commence avec quelque-chose de simple:
```yaml
algorithm:
   initial_temp: 1000
   min_temp: 0.1
   cooling_factor: 0.95
   max_iteration_number: 1000
devices:
   - name: "cumulus"
     entity_id: "switch.prise_cumulus_commutateur"
     power_max: 505
     check_usable_template: "{{ True }}"
     duration_min: 60
     duration_stop_min: 60
     action_mode: "service_call"
     activation_service: "switch.turn_on"
     deactivation_service: "switch.turn_off"
```

**Reply by Chrisdie59** [reply]
Top merci j essai cela ce soir
Bonne journée

**Reply by Chrisdie59** [reply]
Bonsoir

j'ai ajouté ton code au configuration.yaml mais lorsque je fais une vérification avant redemarrage j'ai cette alerte 
![Capture d’écran 2025-02-11 205726](https://github.com/user-attachments/assets/23708076-76f7-47d3-966d-a2e566bd333a)

**Reply by jmcollin78** [reply]
IL faut le mettre dans le fichier sonar_optimizer.yaml et pas dans le configuration.yaml directement. Tu as bien un fichier solar_optimizer.yaml ?

**Reply by Chrisdie59** [reply]
Bonjour oui j ai bien un fichier solar_optimizer.yaml sur la même racine que config... mais qd j ajoute la petite ligne sur le configuration du fichier à inclure et que je lance une vérification de mon configuration.yaml sur outil de développement celui ci tourne en rond sans jamais me dire que le fichier config est bon
Dois je qd même rebooter ha ?
C est pour cela que j ai essaye de copier le code dans le configuration.yaml

**Reply by jmcollin78** [reply]
> celui ci tourne en rond sans jamais me dire que le fichier config est bon

Surtout pas, HA ne va pas démarrer. Il faut que tu corriges le problèmes avant.
Donnes moi ton fichier `configuration.yml` en le formattant avec <> et en évitant tes éventuels mode de passe.
Mets moi aussi ton fichier `solar_optimizer.yaml` que je regarde.

**Reply by Chrisdie59** [reply]
Bonsoir
Voici le fichier Solar_optimizer
```
algorithm:
   initial_temp: 1000
   min_temp: 0.1
   cooling_factor: 0.95
   max_iteration_number: 1000
devices:
   - name: "cumulus"
     entity_id: "switch.prise_cumulus_commutateur"
     power_max: 505
     check_usable_template: "{{ true }}"
     duration_min: 60
     duration_stop_min: 60
     action_mode: "service_call"
     activation_service: "switch.turn_on"
     deactivation_service: "switch.turn_off"
     max_on_time_per_day_min: 360
     offpeak_time: 23:30
     min_on_day_per_day_min: 359``
```

**Reply by Chrisdie59** [reply]
et voici mon configuration.yaml

```
# Chargement des configurations par défaut
default_config:

# Chargement des thèmes
frontend:
  themes: !include_dir_merge_named themes

# Configuration des capteurs binaires
binary_sensor:
  - platform: meteoalarm
    country: "France"
    province: "Paris"
    language: "fr-FR"

# Configuration des capteurs template pour Tempo price

template: 

  #total pour graphe consommation
  
  - sensor:
      - name: "Total puissance prises"
        unit_of_measurement: "W"
        state: "{{ states('sensor.prise_one_puissance') | float(0) + states('sensor.puissance_lave_vaisselle') | float(0) + states('sensor.prise_cumulus_puissance') | float(0) + states('sensor.prise_aspirateur_puissance') | float(0) + states('sensor.seche_linge_puissance') | float(0) + states('sensor.prise_tv_puissance') | float(0) + states('sensor.prise_pc_lulu_puissance') | float(0) + states('sensor.prise_two_puissance') | float(0) }}"
  - sensor:
      - name: "Conso totale 24h"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.prise_one_conso_24h') | float(0) + states('sensor.lave_vaisselle_conso_24h') | float(0) + states('sensor.prise_cumulus_conso_24h') | float(0) + states('sensor.prise_aspi_conso_24h') | float(0) + states('sensor.prise_seche_linge_conso_24h') | float(0) + states('sensor.prise_tv_chambre_conso_24h') | float(0) + states('sensor.prise_pc_lucas_conso_24h') | float(0) + states('sensor.prise_two_conso_24h') | float(0) }}"

  - !include tempoprice.yaml
  - !include template_energy.yaml

# Inclusion des fichiers spécifiques pour les input_number

input_number: !include input_numbers.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  host: XXXXXXX-influxdb
  port: 8086
  database: HomeassistantDBCD
  username: XXXXXX
  password: XXXXXX
  max_retries: 3
  default_measurement: state
  
sensor:
  - platform: solarman
    name: Solarman
    inverter_host: xxxxxx
    inverter_port: 8899
    inverter_serial: xxxxxxxx
    inverter_mb_slaveid: 1
    lookup_file: deye_2mppt.yaml
    
# sensor pour graphique consommation electrique sur 24H
    
  - platform: integration
    source: sensor.prise_one_puissance
    name: prise_one_conso_24h
    unit_prefix: k
    round: 2
    
  - platform: integration
    source: sensor.prise_cumulus_puissance
    name: prise_cumulus_conso_24h
    unit_prefix: k
    round: 2  
    
  - platform: integration
    source: sensor.solarman_total_ac_output_power_active
    name: prise_solarman_conso_24h
    unit_prefix: k
    round: 2  
    
  - platform: integration
    source: sensor.prise_aspirateur_puissance
    name: prise_aspi_conso_24h
    unit_prefix: k
    round: 2    
    
  - platform: integration
    source: sensor.prise_lave_vaiselle
    name: prise_lave_vaisselle_conso_24h
    unit_prefix: k
    round: 2   
    
  - platform: integration
    source: sensor.seche_linge_puissance
    name: prise_seche_linge_conso_24h
    unit_prefix: k
    round: 2  
    
  - platform: integration
    source: sensor.prise_tv_puissance
    name: prise_tv_chambre_conso_24h
    unit_prefix: k
    round: 2 
    
  - platform: integration
    source: sensor.prise_pc_lulu_puissance
    name: prise_pc_lucas_conso_24h
    unit_prefix: k
    round: 2 
    
  - platform: integration
    source: sensor.prise_two_puissance
    name: prise_two_conso_24h
    unit_prefix: k
    round: 2 

#pour solar optimizer pilote sensor

solar_optimizer: !include solar_optimizer.yaml
```
