### ISSUE TITLE
[Feature request] add checkbox to inverse sign of current for net instantaneous consumption and battery power

### ISSUE THREAD

**Issue by M3c4tr0x** [jmcollin78/solar_optimizer#116]
On my installation, my inverter (HYD-6000-EP) correctly provides me with the information requested by Solar Optimizer. The problem is that the signs of the grid current import/export and the battery power are opposite to those requested by Solar Optimizer.

Would it be possible to consider a checkbox in the Solar Optimizer configuration to allow native use of these entities, without having to create virtual entities specifically for this integration?

**Comment by jmcollin78** [comment]
Hello, it is preferable to have you own template that calculate the correct value. That is the best you can do. I cannot integrate all users use cases and situations.

example of template:
```
- sensor:
    - name: "Total puissance produite instantanée (W)"
      icon: mdi:solar-power-variant
      unique_id: total_power_produite_w
      device_class: power
      unit_of_measurement: "W"
      state_class: measurement
      state: >
        {% set power = [states('sensor.envoy_122307065303_current_power_production') | float(default=0), 0] | max %}
        {{ power | round(2) }}
      availability: "{{ is_number(states('sensor.envoy_122307065303_current_power_production')) }}"
```
