### ISSUE TITLE
Day without enough solar production

### ISSUE THREAD

**Issue by hatch01** [jmcollin78/solar_optimizer#37]
**Is your feature request related to a problem? Please describe.**
If we are on a cloudy day, the water eater would not be turned on in the day and I will get cold water.

**Describe the solution you'd like**
Add a parameter "minimum enabled duration per day" for the entities.

**Describe alternatives you've considered**
I could maybe work around by just measuring the duration in the evening and enable it then, but this will not be optimized with the solar production.

**Comment by MrBLJ** [comment]
Workaround for Optimizing Solar Excess for Water Heating

_Disclaimer: I primarily use my solar excess to charge my cars, so the water-heating part of my setup isn't fully optimized yet._

## Method

### Create a Sensor to Track Device Usage

You have two options:

1. Track the Number of Hours the Device was Used

```yaml
# Sensor - History stats.
sensor:
  # Heating Duration Today
  # Number of hours of heating done today.
  - platform: history_stats
    name: Heating Duration Today
    entity_id: sensor.heated_floor_status
    state: 'heating'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
```

2. Track the Power Consumption per Day

```yaml
# Example configuration.yaml entry
utility_meter:
  energy:
    source: sensor.energy_in_kwh
    cycle: daily
```
### Determine Heating Cycle Specs
On a day without solar injection, turn on your boiler and measure the time it takes to get hot water. This will give you a limit in terms of hours or kWh to use in an automation.

### Create an Automation

- **Trigger**: Every day at a specified time (e.g., when off-peak hours start).
- **Condition**: Power consumption or time of use is below the threshold.
- **Actions**:
  1. Disable solar optimizer.
  2. Turn on the device.
  3. Wait for your tracking sensor to reach the threshold in minutes or power consumption (set a time limit).
  4. Turn off the device.
  5. Enable solar optimizer.

This way, you can run solar optimizer during the day, and finish off heating during offpeak hours.
