### ISSUE TITLE
Maximum On-Time per Device per Day

### ISSUE THREAD

**Issue by pattex007** [jmcollin78/solar_optimizer#47]
My Pool Pump is running 10 hours a day, which is a little bit to long.

it would be great if there is a option like "duration_max_per_day: 120" in minutes in the device section

**Comment by jmcollin78** [comment]
Hello, yes it is a good idea in the direction taken by all change request.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/solar_optimizer/releases/tag/2.0.0.beta1

Please give a try to this pre-release. To use it you should add a `max_on_time_per_day_min: <value in minutes>` in your solar_optimizer.yaml file. Example:

```
solar_optimizer:
  algorithm:
...
    - name: "Equipement name"
      entity_id: "input_boolean.fake_device_g"
      power_max: 1200
      check_usable_template: "{{ True }}"
      duration_min: 1.5
      action_mode: "service_call"
      activation_service: "input_boolean/turn_on"
      deactivation_service: "input_boolean/turn_off"
      battery_soc_threshold: 40
      max_on_time_per_day_min: 30              <------------------ add this
...
```

You will also notice than there is now one device per devices in solar_optimizer.yaml in which you will find some entities:
![Capture d’écran 2024-09-30 à 13 56 50](https://github.com/user-attachments/assets/e07e4851-138f-4c8c-8f01-dfb79ada5c97)

This point can create backward compatibilities issues depending on how you use it.
