### ISSUE TITLE
Power Production not valued

### ISSUE THREAD

**Issue by siegelpeter** [jmcollin78/solar_optimizer#50]
## Version of the custom_component
1.7 la
## Configuration

```yaml


algorithm:
  initial_temp: 1000
  min_temp: 0.1
  cooling_factor: 0.95
  max_iteration_number: 100

devices:
  - name: "Reservoir pump"
    # The switch that controls the tank pump
    entity_id: "switch.eg_bad_licht_schalter"
    # the power of this pump
    power_max: 50
    # Always usable
    # check_usable_template: "{{ True }}"
    # 15 min minimum activation
    duration_min: 15
    # 5 min deactivation minimum
    duration_stop_min: 5
    # On enable/disable via a service call
    action_mode: "service_call"
    # The service enabling the switch
    activation_service: "switch/turn_on"
    # The service to deactivate the switch
    deactivation_service: "switch/turn_off"

```

![grafik](https://github.com/user-attachments/assets/b10115c9-6d4a-41a3-9750-feae39b95009)

Active Power:
![grafik](https://github.com/user-attachments/assets/d4111ef4-30d2-43ae-886b-72b71f17e45e)

net Consumption:
![grafik](https://github.com/user-attachments/assets/a382fcb8-8d84-4245-ae68-46a5d229c2ff)
Is negative when power is exported (most of the day)

## Describe the bug
the device is turned on as soon as there is enough power. This works well. But in the evening there is not enough power the device is not turned off.
The Logs say that power production is not valued. but according to homeassistant it has the value 0. What can i do?

## Debug log

```text

Logger: custom_components.solar_optimizer.coordinator
Quelle: custom_components/solar_optimizer/coordinator.py:116
Integration: Solar Optimizer (Dokumentation, Probleme)
Erstmals aufgetreten: 11. August 2024 um 22:45:20 (99 Vorkommnisse)
Zuletzt protokolliert: 21:05:20

Power production is not valued. Solar Optimizer will be disabled

```
