### ISSUE TITLE
Cards do not show values anymore after upgrade to 2.0

### ISSUE THREAD

**Issue by morris2009** [jmcollin78/solar_optimizer#68]
Hi,
After the upgrade to v2.0 of the component, i don't see any values in the dashboard anymore.
to try and resolve it I did remove the old code for the card template and insert the newer code with the additional features, but the card is still mostly empty.

Most likely I may have forgotten a step somewhere? Can you point me in the right direction.

## Version of the custom_component
version 2.0.0

## Yaml code of actual card
```
type: custom:decluttering-card
template: managed_device
variables:
  - device: switch.solar_optimizer_coolbox
  - secondary_infos: '{{ states(''sensor.athom_smart_plug_v3_f8c6f8_power'') }} W'
  - icon: mdi:power-socket-eu
  - enable_entity: switch.enable_solar_optimizer_coolbox
```
`
![image](https://github.com/user-attachments/assets/27d8dcf8-875b-4a90-84c5-ec34612f1e48)
