### ISSUE TITLE
[Feature Request] - Template for "duration_min" - Easy PR !

### ISSUE THREAD

**Issue by froggy974** [jmcollin78/solar_optimizer#86]
## Version of the custom_component
2.1.1

## Configuration

```yaml

algorithm:
  initial_temp: 1000
  min_temp: 0.1
  cooling_factor: 0.95
  max_iteration_number: 1000
devices:
  - name: "pompe piscine"
    entity_id: "switch.tz3000_pompe_piscine"
    power_max: 650
    #check_usable_template: "{{ is_state('input_boolean.utilisation_pompe_piscine_pour_delestage', 'on') }}"
    #duration_min: {{ float(states('sensor.auto_cycle_duration_abacus'),60) }}
    duration_min: 60
    duration_stop_min: 30
    action_mode: "service_call"
    activation_service: "switch/turn_on"
    deactivation_service: "switch/turn_off"
  - name: "chauffage SPA"
    entity_id: "input_boolean.delestage_surplus_spa"
    power_max: 2800
    #check_usable_template: "{{ is_state('input_boolean.utilisation_pompe_piscine_pour_delestage', 'on') }}"
    duration_min: 30
    duration_stop_min: 10
    action_mode: "service_call"
    activation_service: "input_boolean/turn_on"
    deactivation_service: "input_boolean/turn_off"

```

## Description of the bug
I use the pool pump as a device for solar optimizer
the minimum duration the pump is running each day depends on the water temperature
I would like to use a sensor value for the ` duration_min` in solar optimizer config
i tried this template syntax 
`duration_min: {{ float(states('sensor.auto_cycle_duration_abacus'),60) }}`

which generates an error message

I'm not even sure it's possible to do that ...
Can you confirm ?

## Debug log

```text

Invalid config for 'solar_optimizer' at solar_optimizer.yaml, line 11: expected float for dictionary value 'solar_optimizer->devices->0->duration_min', got "{{ float(states('sensor.auto_cycle_duration_abacus'),60) }}", please check the docs at https://github.com/jmcollin78/solar_optimizer

```
